# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: Vertices to VR
description: Bring Vr to the world with Cardboard
author:
  name: Ada Rose Edwards	
  email: ada@ada.is
  twitter: lady_ada_king
  company: FT Labs

# Grunt handles images and assets.
exclude: ['img', '**.css', '**.js', 'fonts', 'node_modules',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

permalink: /:categories-:title.html

pygments: true
highlighter: pygments

markdown: redcarpet

excerpt_separator: qwertyuiopsdfghjkl
