# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: My Title
description: My Subtitle
author:
  name: Jane Bloggs
  email: fakeemail@123fakestreet.com
  twitter: jbloggs
  company: Acme Inc.

# Grunt handles images and assets.
exclude: ['img', '**.css', '**.js', 'fonts', 'node_modules',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

permalink: pretty

pygments: true
highlighter: pygments
